<%@ Page Language="C#" MasterPageFile="AdminMaster.master"
AutoEventWireup="true" CodeBehind="Signup.aspx.cs"
Inherits="welfareSystem.Signup" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-8 col-lg-10 col-md-12">
        <!-- Signup Form Card -->
        <div class="card shadow-lg border-0 mb-5">
          <div class="card-header bg-gradient-primary text-white py-3">
            <h4 class="mb-0">
              <i class="fas fa-user-plus me-2"></i>User Signup
            </h4>
          </div>
          <div class="card-body p-4">
            <div class="mb-3">
              <label for="txtName" class="form-label fw-semibold">
                <i class="fas fa-user me-2 text-muted"></i>Full Name
              </label>
              <asp:TextBox
                ID="txtName"
                runat="server"
                CssClass="form-control"
                placeholder="Enter your full name"
              />
            </div>

            <div class="mb-3">
              <label for="txtUsername" class="form-label fw-semibold">
                <i class="fas fa-at me-2 text-muted"></i>Username
              </label>
              <asp:TextBox
                ID="txtUsername"
                runat="server"
                CssClass="form-control"
                placeholder="Choose a username"
              />
            </div>

            <div class="mb-3">
              <label for="txtPassword" class="form-label fw-semibold">
                <i class="fas fa-lock me-2 text-muted"></i>Password
              </label>
              <div class="input-group">
                <asp:TextBox
                  ID="txtPassword"
                  runat="server"
                  TextMode="Password"
                  CssClass="form-control"
                  placeholder="Enter password"
                />
                <button
                  type="button"
                  class="btn btn-outline-secondary"
                  onclick="togglePassword()"
                  id="togglePasswordBtn"
                >
                  <i class="fas fa-eye" id="eyeIcon"></i>
                </button>
              </div>
            </div>

            <div class="mb-4">
              <label for="ddlRole" class="form-label fw-semibold">
                <i class="fas fa-user-tag me-2 text-muted"></i>Role
              </label>
              <asp:DropDownList ID="ddlRole" runat="server" CssClass="form-select">
              </asp:DropDownList>
            </div>

            <div class="d-grid">
              <asp:Button
                ID="btnSignup"
                runat="server"
                Text="Sign Up"
                CssClass="btn btn-primary btn-lg"
                OnClick="btnSignup_Click"
              />
            </div>
          </div>
        </div>

        <!-- User List Card -->
        <div class="card shadow-lg border-0">
          <div class="card-header bg-gradient-success text-white py-3">
            <h4 class="mb-0">
              <i class="fas fa-users me-2"></i>User List
            </h4>
          </div>
          <div class="card-body p-4">
            <div class="table-responsive">
              <asp:GridView
                ID="gvUsers"
                runat="server"
                AutoGenerateColumns="False"
                CssClass="table table-hover table-bordered align-middle"
                DataKeyNames="UserId"
                AutoGenerateEditButton="True"
                AutoGenerateDeleteButton="True"
                OnRowEditing="gvUsers_RowEditing"
                OnRowCancelingEdit="gvUsers_RowCancelingEdit"
                OnRowUpdating="gvUsers_RowUpdating"
                OnRowDeleting="gvUsers_RowDeleting"
                HeaderStyle-CssClass="table-dark"
              >
                <Columns>
                  <asp:BoundField
                    DataField="UserId"
                    HeaderText="ID"
                    ReadOnly="True"
                    ItemStyle-Width="80"
                  />

                  <asp:BoundField DataField="FullName" HeaderText="Full Name" />

                  <asp:BoundField DataField="Username" HeaderText="Username" />

                  <asp:BoundField DataField="Password" HeaderText="Password" />

                  <%--<asp:BoundField DataField="RoleName" HeaderText="Role" />--%>
                </Columns>
              </asp:GridView>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <style>
    .bg-gradient-primary {
      background: var(--primary-red);
    }
    .bg-gradient-success {
      background: var(--dashboard-color);
    }
    .card {
      border-radius: 12px;
    }
    .form-control:focus, .form-select:focus {
      border-color: var(--security-color);
      box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
    }
    .btn-primary {
      background: var(--primary-red);
      border: none;
    }
    .btn-primary:hover {
      background: #a01e2b;
      transform: translateY(-2px);
      box-shadow: 0 4px 12px rgba(200, 35, 51, 0.4);
    }
    .table thead th {
      border-top: none;
    }
  </style>

  <script>
    function togglePassword() {
      var passwordTextBox = document.getElementById('<%= txtPassword.ClientID %>');
      var eyeIcon = document.getElementById('eyeIcon');

      if (passwordTextBox.type === 'password') {
        passwordTextBox.type = 'text';
        eyeIcon.classList.remove('fa-eye');
        eyeIcon.classList.add('fa-eye-slash');
      } else {
        passwordTextBox.type = 'password';
        eyeIcon.classList.remove('fa-eye-slash');
        eyeIcon.classList.add('fa-eye');
      }
    }
  </script>
</asp:Content>
