<%@ Page Language="C#"
MasterPageFile="AdminMaster.master"
AutoEventWireup="true"
CodeBehind="Signup.aspx.cs"
Inherits="welfareSystem.Signup" %>

<asp:Content ID="Content1"
ContentPlaceHolderID="MainContent"
runat="server">

<div class="container mt-4">

    <h3>User Signup</h3>
     <div class="row justify-content-center">
        <div class="col-xl-10">
            <div class="card shadow-sm border-0 overflow-hidden">
                <div style="height: 4px; background: linear-gradient(90deg, #c82333, #dc3545);"></div>
    <asp:TextBox ID="txtName"
        runat="server"
        CssClass="form-control"
        placeholder="Full Name" />

    <br />

    <asp:TextBox ID="txtUsername"
        runat="server"
        CssClass="form-control"
        placeholder="Username" />

    <br />

    <asp:TextBox ID="txtPassword"
        runat="server"
        TextMode="Password"
        CssClass="form-control"
        placeholder="Password" />

    <br />

    <asp:DropDownList ID="ddlRole"
        runat="server"
        CssClass="form-control">
    </asp:DropDownList>

    <br />

    <asp:Button ID="btnSignup"
        runat="server"
        Text="Sign Up"
        CssClass="btn btn-primary"
        OnClick="btnSignup_Click" />

    <hr />

    <h3>User List</h3>

    <asp:GridView ID="gvUsers"
        runat="server"
        AutoGenerateColumns="False"
        CssClass="table table-bordered table-striped"
        DataKeyNames="UserId"
        AutoGenerateEditButton="True"
        AutoGenerateDeleteButton="True"
        OnRowEditing="gvUsers_RowEditing"
        OnRowCancelingEdit="gvUsers_RowCancelingEdit"
        OnRowUpdating="gvUsers_RowUpdating"
        OnRowDeleting="gvUsers_RowDeleting">

        <Columns>

            <asp:BoundField
                DataField="UserId"
                HeaderText="ID"
                ReadOnly="True" />

            <asp:BoundField
                DataField="FullName"
                HeaderText="Full Name" />

            <asp:BoundField
                DataField="Username"
                HeaderText="Username" />

            <asp:BoundField
                DataField="Password"
                HeaderText="Password" />

            <%--<asp:BoundField
                DataField="RoleName"
                HeaderText="Role"/>--%>

        </Columns>

    </asp:GridView>
</div>
            </div>
         </div>
</div>

</asp:Content>